import type { Metadata } from "next";
import "./variables.scss";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Sauté",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  );
}
